"""Add is_verified to User model

Revision ID: 493f7706c948
Revises: c0ce789c0467
Create Date: 2025-12-29 20:31:06.649621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493f7706c948'
down_revision = 'c0ce789c0467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
