"""Add performance indexes

Revision ID: c0ce789c0467
Revises: 513943b5399a
Create Date: 2025-12-29 11:10:26.352830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ce789c0467'
down_revision = '513943b5399a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tenant_phone'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tenant_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenant_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_phone'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_phone'), ['phone'])

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_property_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_phone'))
        batch_op.create_unique_constraint(batch_op.f('uq_tenant_phone'), ['phone'])

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_user_id'))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_property_id'))

    # ### end Alembic commands ###
