"""Add user_id to Tenant with fixed naming

Revision ID: f8257860ef28
Revises: 6667569e4dfb
Create Date: 2025-12-29 03:35:47.654376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8257860ef28'
down_revision = '6667569e4dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_tenant_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_tenant_phone'), ['phone'])
        batch_op.create_foreign_key(batch_op.f('fk_tenant_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tenant_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_tenant_phone'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_tenant_email'), type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
