"""add uploads

Revision ID: fa38237f9fb8
Revises: e729d0c899e5
Create Date: 2025-12-29 04:26:30.527461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa38237f9fb8'
down_revision = 'e729d0c899e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.Text(), nullable=True))

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('documents')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
